// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Coefficients
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coefficientsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Coefficients";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EffectiveDate("EffectiveDate"),
		EffectiveDateStart("EffectiveDateStart"),
		EffectiveDateEnd("EffectiveDateEnd"),
		Politeness_coef("Politeness_coef"),
		Professionalism_coef("Professionalism_coef"),
		Hygiene_coef("Hygiene_coef"),
		Availibility_coef("Availibility_coef"),
		DateOfLastEdit("DateOfLastEdit"),
		chooses("MyFirstModule.chooses");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Coefficients(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Coefficients(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coefficientsMendixObject)
	{
		if (coefficientsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, coefficientsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.coefficientsMendixObject = coefficientsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Coefficients.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Coefficients initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Coefficients.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Coefficients initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Coefficients(context, mendixObject);
	}

	public static myfirstmodule.proxies.Coefficients load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Coefficients.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Coefficients> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Coefficients.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of EffectiveDate
	 * @param effectivedate
	 */
	public final myfirstmodule.proxies.Dates getEffectiveDate()
	{
		return getEffectiveDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveDate
	 */
	public final myfirstmodule.proxies.Dates getEffectiveDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EffectiveDate.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Dates.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EffectiveDate
	 * @param effectivedate
	 */
	public final void setEffectiveDate(myfirstmodule.proxies.Dates effectivedate)
	{
		setEffectiveDate(getContext(), effectivedate);
	}

	/**
	 * Set value of EffectiveDate
	 * @param context
	 * @param effectivedate
	 */
	public final void setEffectiveDate(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dates effectivedate)
	{
		if (effectivedate != null) {
			getMendixObject().setValue(context, MemberNames.EffectiveDate.toString(), effectivedate.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EffectiveDate.toString(), null);
		}
	}

	/**
	 * @return value of EffectiveDateStart
	 */
	public final java.util.Date getEffectiveDateStart()
	{
		return getEffectiveDateStart(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveDateStart
	 */
	public final java.util.Date getEffectiveDateStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EffectiveDateStart.toString());
	}

	/**
	 * Set value of EffectiveDateStart
	 * @param effectivedatestart
	 */
	public final void setEffectiveDateStart(java.util.Date effectivedatestart)
	{
		setEffectiveDateStart(getContext(), effectivedatestart);
	}

	/**
	 * Set value of EffectiveDateStart
	 * @param context
	 * @param effectivedatestart
	 */
	public final void setEffectiveDateStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date effectivedatestart)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveDateStart.toString(), effectivedatestart);
	}

	/**
	 * @return value of EffectiveDateEnd
	 */
	public final java.util.Date getEffectiveDateEnd()
	{
		return getEffectiveDateEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveDateEnd
	 */
	public final java.util.Date getEffectiveDateEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EffectiveDateEnd.toString());
	}

	/**
	 * Set value of EffectiveDateEnd
	 * @param effectivedateend
	 */
	public final void setEffectiveDateEnd(java.util.Date effectivedateend)
	{
		setEffectiveDateEnd(getContext(), effectivedateend);
	}

	/**
	 * Set value of EffectiveDateEnd
	 * @param context
	 * @param effectivedateend
	 */
	public final void setEffectiveDateEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date effectivedateend)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveDateEnd.toString(), effectivedateend);
	}

	/**
	 * @return value of Politeness_coef
	 */
	public final java.math.BigDecimal getPoliteness_coef()
	{
		return getPoliteness_coef(getContext());
	}

	/**
	 * @param context
	 * @return value of Politeness_coef
	 */
	public final java.math.BigDecimal getPoliteness_coef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Politeness_coef.toString());
	}

	/**
	 * Set value of Politeness_coef
	 * @param politeness_coef
	 */
	public final void setPoliteness_coef(java.math.BigDecimal politeness_coef)
	{
		setPoliteness_coef(getContext(), politeness_coef);
	}

	/**
	 * Set value of Politeness_coef
	 * @param context
	 * @param politeness_coef
	 */
	public final void setPoliteness_coef(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal politeness_coef)
	{
		getMendixObject().setValue(context, MemberNames.Politeness_coef.toString(), politeness_coef);
	}

	/**
	 * @return value of Professionalism_coef
	 */
	public final java.math.BigDecimal getProfessionalism_coef()
	{
		return getProfessionalism_coef(getContext());
	}

	/**
	 * @param context
	 * @return value of Professionalism_coef
	 */
	public final java.math.BigDecimal getProfessionalism_coef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Professionalism_coef.toString());
	}

	/**
	 * Set value of Professionalism_coef
	 * @param professionalism_coef
	 */
	public final void setProfessionalism_coef(java.math.BigDecimal professionalism_coef)
	{
		setProfessionalism_coef(getContext(), professionalism_coef);
	}

	/**
	 * Set value of Professionalism_coef
	 * @param context
	 * @param professionalism_coef
	 */
	public final void setProfessionalism_coef(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal professionalism_coef)
	{
		getMendixObject().setValue(context, MemberNames.Professionalism_coef.toString(), professionalism_coef);
	}

	/**
	 * @return value of Hygiene_coef
	 */
	public final java.math.BigDecimal getHygiene_coef()
	{
		return getHygiene_coef(getContext());
	}

	/**
	 * @param context
	 * @return value of Hygiene_coef
	 */
	public final java.math.BigDecimal getHygiene_coef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Hygiene_coef.toString());
	}

	/**
	 * Set value of Hygiene_coef
	 * @param hygiene_coef
	 */
	public final void setHygiene_coef(java.math.BigDecimal hygiene_coef)
	{
		setHygiene_coef(getContext(), hygiene_coef);
	}

	/**
	 * Set value of Hygiene_coef
	 * @param context
	 * @param hygiene_coef
	 */
	public final void setHygiene_coef(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal hygiene_coef)
	{
		getMendixObject().setValue(context, MemberNames.Hygiene_coef.toString(), hygiene_coef);
	}

	/**
	 * @return value of Availibility_coef
	 */
	public final java.math.BigDecimal getAvailibility_coef()
	{
		return getAvailibility_coef(getContext());
	}

	/**
	 * @param context
	 * @return value of Availibility_coef
	 */
	public final java.math.BigDecimal getAvailibility_coef(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Availibility_coef.toString());
	}

	/**
	 * Set value of Availibility_coef
	 * @param availibility_coef
	 */
	public final void setAvailibility_coef(java.math.BigDecimal availibility_coef)
	{
		setAvailibility_coef(getContext(), availibility_coef);
	}

	/**
	 * Set value of Availibility_coef
	 * @param context
	 * @param availibility_coef
	 */
	public final void setAvailibility_coef(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal availibility_coef)
	{
		getMendixObject().setValue(context, MemberNames.Availibility_coef.toString(), availibility_coef);
	}

	/**
	 * @return value of DateOfLastEdit
	 */
	public final java.util.Date getDateOfLastEdit()
	{
		return getDateOfLastEdit(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfLastEdit
	 */
	public final java.util.Date getDateOfLastEdit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfLastEdit.toString());
	}

	/**
	 * Set value of DateOfLastEdit
	 * @param dateoflastedit
	 */
	public final void setDateOfLastEdit(java.util.Date dateoflastedit)
	{
		setDateOfLastEdit(getContext(), dateoflastedit);
	}

	/**
	 * Set value of DateOfLastEdit
	 * @param context
	 * @param dateoflastedit
	 */
	public final void setDateOfLastEdit(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateoflastedit)
	{
		getMendixObject().setValue(context, MemberNames.DateOfLastEdit.toString(), dateoflastedit);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of chooses
	 */
	public final myfirstmodule.proxies.Manager getchooses() throws com.mendix.core.CoreException
	{
		return getchooses(getContext());
	}

	/**
	 * @param context
	 * @return value of chooses
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Manager getchooses(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Manager result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.chooses.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Manager.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of chooses
	 * @param chooses
	 */
	public final void setchooses(myfirstmodule.proxies.Manager chooses)
	{
		setchooses(getContext(), chooses);
	}

	/**
	 * Set value of chooses
	 * @param context
	 * @param chooses
	 */
	public final void setchooses(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Manager chooses)
	{
		if (chooses == null) {
			getMendixObject().setValue(context, MemberNames.chooses.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.chooses.toString(), chooses.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coefficientsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Coefficients that = (myfirstmodule.proxies.Coefficients) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
