// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Dates
{
	Jan23(new java.lang.String[][] { new java.lang.String[] { "en_US", "January 2023" } }),
	Feb23(new java.lang.String[][] { new java.lang.String[] { "en_US", "February 2023" } }),
	Mar23(new java.lang.String[][] { new java.lang.String[] { "en_US", "March 2023" } }),
	Apr23(new java.lang.String[][] { new java.lang.String[] { "en_US", "April 2023" } }),
	May23(new java.lang.String[][] { new java.lang.String[] { "en_US", "May 2023" } }),
	Jun23(new java.lang.String[][] { new java.lang.String[] { "en_US", "June 2023" } }),
	Jul23(new java.lang.String[][] { new java.lang.String[] { "en_US", "July 2023" } }),
	Aug23(new java.lang.String[][] { new java.lang.String[] { "en_US", "August 2023" } }),
	Sep23(new java.lang.String[][] { new java.lang.String[] { "en_US", "September 2023" } }),
	Oct23(new java.lang.String[][] { new java.lang.String[] { "en_US", "October 2023" } }),
	Nov23(new java.lang.String[][] { new java.lang.String[] { "en_US", "November 2023" } }),
	Dec23(new java.lang.String[][] { new java.lang.String[] { "en_US", "December 2023" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Dates(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
