// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Dentist_Coefficients_DTO
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dentist_Coefficients_DTOMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Dentist_Coefficients_DTO";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FirstName("FirstName"),
		LastName("LastName"),
		Email("Email"),
		Politeness_finalgrade("Politeness_finalgrade"),
		Professionalism_finalgrade("Professionalism_finalgrade"),
		Hygiene_finalgrade("Hygiene_finalgrade"),
		Availibility_finalgrade("Availibility_finalgrade"),
		Sum("Sum"),
		Month("Month"),
		EffectiveDateStart("EffectiveDateStart"),
		EffectiveDateEnd("EffectiveDateEnd"),
		Name("Name");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dentist_Coefficients_DTO(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Dentist_Coefficients_DTO(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dentist_Coefficients_DTOMendixObject)
	{
		if (dentist_Coefficients_DTOMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dentist_Coefficients_DTOMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dentist_Coefficients_DTOMendixObject = dentist_Coefficients_DTOMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Dentist_Coefficients_DTO.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Dentist_Coefficients_DTO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Dentist_Coefficients_DTO.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Dentist_Coefficients_DTO initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Dentist_Coefficients_DTO(context, mendixObject);
	}

	public static myfirstmodule.proxies.Dentist_Coefficients_DTO load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Dentist_Coefficients_DTO.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName()
	{
		return getFirstName(getContext());
	}

	/**
	 * @param context
	 * @return value of FirstName
	 */
	public final java.lang.String getFirstName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FirstName.toString());
	}

	/**
	 * Set value of FirstName
	 * @param firstname
	 */
	public final void setFirstName(java.lang.String firstname)
	{
		setFirstName(getContext(), firstname);
	}

	/**
	 * Set value of FirstName
	 * @param context
	 * @param firstname
	 */
	public final void setFirstName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.FirstName.toString(), firstname);
	}

	/**
	 * @return value of LastName
	 */
	public final java.lang.String getLastName()
	{
		return getLastName(getContext());
	}

	/**
	 * @param context
	 * @return value of LastName
	 */
	public final java.lang.String getLastName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastName.toString());
	}

	/**
	 * Set value of LastName
	 * @param lastname
	 */
	public final void setLastName(java.lang.String lastname)
	{
		setLastName(getContext(), lastname);
	}

	/**
	 * Set value of LastName
	 * @param context
	 * @param lastname
	 */
	public final void setLastName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.LastName.toString(), lastname);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Politeness_finalgrade
	 */
	public final java.math.BigDecimal getPoliteness_finalgrade()
	{
		return getPoliteness_finalgrade(getContext());
	}

	/**
	 * @param context
	 * @return value of Politeness_finalgrade
	 */
	public final java.math.BigDecimal getPoliteness_finalgrade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Politeness_finalgrade.toString());
	}

	/**
	 * Set value of Politeness_finalgrade
	 * @param politeness_finalgrade
	 */
	public final void setPoliteness_finalgrade(java.math.BigDecimal politeness_finalgrade)
	{
		setPoliteness_finalgrade(getContext(), politeness_finalgrade);
	}

	/**
	 * Set value of Politeness_finalgrade
	 * @param context
	 * @param politeness_finalgrade
	 */
	public final void setPoliteness_finalgrade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal politeness_finalgrade)
	{
		getMendixObject().setValue(context, MemberNames.Politeness_finalgrade.toString(), politeness_finalgrade);
	}

	/**
	 * @return value of Professionalism_finalgrade
	 */
	public final java.math.BigDecimal getProfessionalism_finalgrade()
	{
		return getProfessionalism_finalgrade(getContext());
	}

	/**
	 * @param context
	 * @return value of Professionalism_finalgrade
	 */
	public final java.math.BigDecimal getProfessionalism_finalgrade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Professionalism_finalgrade.toString());
	}

	/**
	 * Set value of Professionalism_finalgrade
	 * @param professionalism_finalgrade
	 */
	public final void setProfessionalism_finalgrade(java.math.BigDecimal professionalism_finalgrade)
	{
		setProfessionalism_finalgrade(getContext(), professionalism_finalgrade);
	}

	/**
	 * Set value of Professionalism_finalgrade
	 * @param context
	 * @param professionalism_finalgrade
	 */
	public final void setProfessionalism_finalgrade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal professionalism_finalgrade)
	{
		getMendixObject().setValue(context, MemberNames.Professionalism_finalgrade.toString(), professionalism_finalgrade);
	}

	/**
	 * @return value of Hygiene_finalgrade
	 */
	public final java.math.BigDecimal getHygiene_finalgrade()
	{
		return getHygiene_finalgrade(getContext());
	}

	/**
	 * @param context
	 * @return value of Hygiene_finalgrade
	 */
	public final java.math.BigDecimal getHygiene_finalgrade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Hygiene_finalgrade.toString());
	}

	/**
	 * Set value of Hygiene_finalgrade
	 * @param hygiene_finalgrade
	 */
	public final void setHygiene_finalgrade(java.math.BigDecimal hygiene_finalgrade)
	{
		setHygiene_finalgrade(getContext(), hygiene_finalgrade);
	}

	/**
	 * Set value of Hygiene_finalgrade
	 * @param context
	 * @param hygiene_finalgrade
	 */
	public final void setHygiene_finalgrade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal hygiene_finalgrade)
	{
		getMendixObject().setValue(context, MemberNames.Hygiene_finalgrade.toString(), hygiene_finalgrade);
	}

	/**
	 * @return value of Availibility_finalgrade
	 */
	public final java.math.BigDecimal getAvailibility_finalgrade()
	{
		return getAvailibility_finalgrade(getContext());
	}

	/**
	 * @param context
	 * @return value of Availibility_finalgrade
	 */
	public final java.math.BigDecimal getAvailibility_finalgrade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Availibility_finalgrade.toString());
	}

	/**
	 * Set value of Availibility_finalgrade
	 * @param availibility_finalgrade
	 */
	public final void setAvailibility_finalgrade(java.math.BigDecimal availibility_finalgrade)
	{
		setAvailibility_finalgrade(getContext(), availibility_finalgrade);
	}

	/**
	 * Set value of Availibility_finalgrade
	 * @param context
	 * @param availibility_finalgrade
	 */
	public final void setAvailibility_finalgrade(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal availibility_finalgrade)
	{
		getMendixObject().setValue(context, MemberNames.Availibility_finalgrade.toString(), availibility_finalgrade);
	}

	/**
	 * @return value of Sum
	 */
	public final java.math.BigDecimal getSum()
	{
		return getSum(getContext());
	}

	/**
	 * @param context
	 * @return value of Sum
	 */
	public final java.math.BigDecimal getSum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Sum.toString());
	}

	/**
	 * Set value of Sum
	 * @param sum
	 */
	public final void setSum(java.math.BigDecimal sum)
	{
		setSum(getContext(), sum);
	}

	/**
	 * Set value of Sum
	 * @param context
	 * @param sum
	 */
	public final void setSum(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sum)
	{
		getMendixObject().setValue(context, MemberNames.Sum.toString(), sum);
	}

	/**
	 * Set value of Month
	 * @param month
	 */
	public final myfirstmodule.proxies.Dates getMonth()
	{
		return getMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of Month
	 */
	public final myfirstmodule.proxies.Dates getMonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Month.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Dates.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Month
	 * @param month
	 */
	public final void setMonth(myfirstmodule.proxies.Dates month)
	{
		setMonth(getContext(), month);
	}

	/**
	 * Set value of Month
	 * @param context
	 * @param month
	 */
	public final void setMonth(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Dates month)
	{
		if (month != null) {
			getMendixObject().setValue(context, MemberNames.Month.toString(), month.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Month.toString(), null);
		}
	}

	/**
	 * @return value of EffectiveDateStart
	 */
	public final java.util.Date getEffectiveDateStart()
	{
		return getEffectiveDateStart(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveDateStart
	 */
	public final java.util.Date getEffectiveDateStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EffectiveDateStart.toString());
	}

	/**
	 * Set value of EffectiveDateStart
	 * @param effectivedatestart
	 */
	public final void setEffectiveDateStart(java.util.Date effectivedatestart)
	{
		setEffectiveDateStart(getContext(), effectivedatestart);
	}

	/**
	 * Set value of EffectiveDateStart
	 * @param context
	 * @param effectivedatestart
	 */
	public final void setEffectiveDateStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date effectivedatestart)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveDateStart.toString(), effectivedatestart);
	}

	/**
	 * @return value of EffectiveDateEnd
	 */
	public final java.util.Date getEffectiveDateEnd()
	{
		return getEffectiveDateEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of EffectiveDateEnd
	 */
	public final java.util.Date getEffectiveDateEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EffectiveDateEnd.toString());
	}

	/**
	 * Set value of EffectiveDateEnd
	 * @param effectivedateend
	 */
	public final void setEffectiveDateEnd(java.util.Date effectivedateend)
	{
		setEffectiveDateEnd(getContext(), effectivedateend);
	}

	/**
	 * Set value of EffectiveDateEnd
	 * @param context
	 * @param effectivedateend
	 */
	public final void setEffectiveDateEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date effectivedateend)
	{
		getMendixObject().setValue(context, MemberNames.EffectiveDateEnd.toString(), effectivedateend);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dentist_Coefficients_DTOMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Dentist_Coefficients_DTO that = (myfirstmodule.proxies.Dentist_Coefficients_DTO) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
