// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class EOTM_doc extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.EOTM_doc";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		eotm_doc_rel("MyFirstModule.eotm_doc_rel");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EOTM_doc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EOTM_doc(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject eOTM_docMendixObject)
	{
		super(context, eOTM_docMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, eOTM_docMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'EOTM_doc.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.EOTM_doc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.EOTM_doc.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.EOTM_doc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.EOTM_doc(context, mendixObject);
	}

	public static myfirstmodule.proxies.EOTM_doc load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.EOTM_doc.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.EOTM_doc> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.EOTM_doc.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of eotm_doc_rel
	 */
	public final myfirstmodule.proxies.Employee_of_the_month geteotm_doc_rel() throws com.mendix.core.CoreException
	{
		return geteotm_doc_rel(getContext());
	}

	/**
	 * @param context
	 * @return value of eotm_doc_rel
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Employee_of_the_month geteotm_doc_rel(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Employee_of_the_month result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.eotm_doc_rel.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Employee_of_the_month.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of eotm_doc_rel
	 * @param eotm_doc_rel
	 */
	public final void seteotm_doc_rel(myfirstmodule.proxies.Employee_of_the_month eotm_doc_rel)
	{
		seteotm_doc_rel(getContext(), eotm_doc_rel);
	}

	/**
	 * Set value of eotm_doc_rel
	 * @param context
	 * @param eotm_doc_rel
	 */
	public final void seteotm_doc_rel(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Employee_of_the_month eotm_doc_rel)
	{
		if (eotm_doc_rel == null) {
			getMendixObject().setValue(context, MemberNames.eotm_doc_rel.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.eotm_doc_rel.toString(), eotm_doc_rel.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.EOTM_doc that = (myfirstmodule.proxies.EOTM_doc) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
