// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Materials
{
	Wax_tools(new java.lang.String[][] { new java.lang.String[] { "en_US", "Wax tools" } }),
	Stones(new java.lang.String[][] { new java.lang.String[] { "en_US", "Stones" } }),
	Cleaning_alcohol(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cleaning alcohol" } }),
	Cements(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cements" } }),
	IV_supplies(new java.lang.String[][] { new java.lang.String[] { "en_US", "IV supplies" } }),
	Cleaning_paste(new java.lang.String[][] { new java.lang.String[] { "en_US", "Cleaning paste" } }),
	EKG_supplies(new java.lang.String[][] { new java.lang.String[] { "en_US", "EKG supplies" } }),
	Products_to_treat_dry_mouth(new java.lang.String[][] { new java.lang.String[] { "en_US", "Products to treat dry mouth" } }),
	Whiteners(new java.lang.String[][] { new java.lang.String[] { "en_US", "Whiteners" } }),
	Acrylic_liquid(new java.lang.String[][] { new java.lang.String[] { "en_US", "Acrylic liquid" } }),
	Powder(new java.lang.String[][] { new java.lang.String[] { "en_US", "Powder" } }),
	Alloy(new java.lang.String[][] { new java.lang.String[] { "en_US", "Alloy" } }),
	Fluoride(new java.lang.String[][] { new java.lang.String[] { "en_US", "Fluoride" } }),
	Toothpaste(new java.lang.String[][] { new java.lang.String[] { "en_US", "Toothpaste" } }),
	Painkillers(new java.lang.String[][] { new java.lang.String[] { "en_US", "Painkiller" } }),
	Antibiotic(new java.lang.String[][] { new java.lang.String[] { "en_US", "Antibiotic" } }),
	Denture(new java.lang.String[][] { new java.lang.String[] { "en_US", "Denture" } }),
	Retainer(new java.lang.String[][] { new java.lang.String[] { "en_US", "Retainer" } }),
	Gauge(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gauge" } }),
	Wires(new java.lang.String[][] { new java.lang.String[] { "en_US", "Wires" } }),
	Buccal_tubes(new java.lang.String[][] { new java.lang.String[] { "en_US", "Buccal tubes" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Materials(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
